// FR lang variables - Sarki pour Joomla! FR 31-07-09
tinyMCE.addI18n('fr.advanced',{
style_select:"Styles CSS",
font_size:"Taille",
fontdefault:"Police",
block:"Format",
paragraph:"Paragraphe",
div:"Div",
address:"Addresse",
pre:"Pr\u00E9format\u00E9",
h1:"Titre 1",
h2:"Titre 2",
h3:"Titre 3",
h4:"Titre 4",
h5:"Titre 5",
h6:"Titre 6",
blockquote:"Citation - Blockquote",
code:"Code",
samp:"Exemple Code",
dt:"D\u00E9finition",
dd:"Retrait dd",
bold_desc:"Gras (Ctrl+B)",
italic_desc:"Italique (Ctrl+I)",
underline_desc:"Soulign\u00E9 (Ctrl+U)",
striketrough_desc:"Barr\u00E9",
justifyleft_desc:"Aligner \u00E0 gauche",
justifycenter_desc:"Centrer",
justifyright_desc:"Aligner \u00E0 droite",
justifyfull_desc:"Justifier",
bullist_desc:"Liste \u00E0 puce",
numlist_desc:"Liste num\u00E9rot\u00E9e",
outdent_desc:"Diminuer le retrait",
indent_desc:"Augmenter le retrait",
undo_desc:"Annuler (Ctrl+Z)",
redo_desc:"R\u00E9tablir (Ctrl+Y)",
link_desc:"Cr\u00E9er un lien",
unlink_desc:"Supprimer le lien",
image_desc:"Ins\u00E9rer/Editer une image",
cleanup_desc:"Nettoyer/Fermer les balises",
code_desc:"Editer le code HTML",
sub_desc:"Indice",
sup_desc:"Exposant",
hr_desc:"Ins\u00E9rer une ligne horizontale",
removeformat_desc:"Supprimer tous les styles",
custom1_desc:"Votre description personnelle",
forecolor_desc:"Appliquer une couleur au texte",
backcolor_desc:"Appliquer une couleur de fond au texte",
charmap_desc:"Ins\u00E9rer un caract\u00E8re sp\u00E9cial",
visualaid_desc:"Afficher les cadres-lignes des tableaux",
anchor_desc:"Ins\u00E9rer/Editer une ancre",
cut_desc:"Couper",
copy_desc:"Copier",
paste_desc:"Coller",
image_props_desc:"Propri\u00E9t\u00E9 de l'image",
newdocument_desc:"Effacer le contenu de l'\u00E9diteur",
help_desc:"Aide",
blockquote_desc:"Citation - Blockquote",
clipboard_msg:"La fonction Copier/Coller n'est pas activ\u00E9e sous Mozilla et Firefox. En savoir plus ?",
path:"Chemin",
newdocument:"Voulez-vous effacer tout le contenu de l'\u00E9diteur?",
toolbar_focus:"Barre d'outils - Alt+Q, Editeur contenu - Alt-Z, El\u00E9ment suivant - Alt-X",
more_colors:"Plus de couleurs..."
});